# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  codegen:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: run CodeGen
      run: dotnet run 
      working-directory: codegen\Codegen

    - name: verify no changes from CodeGen
      shell: powershell
      run: |
        $changed = git status --porcelain=v1
        if ($changed -ne $null) { throw "CodeGen detected changes" }

  example:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: yarn install
      run: yarn install
 
    - name: build TS
      run: yarn build
      
    - name: build example
      run: yarn windows --no-launch --no-deploy --no-packager --logging
      working-directory: example

    - name: mkdir Appx
      run: md %BUILD_STAGINGDIRECTORY%\appx

    - name: Copy appx package
      run: xcopy /s * %BUILD_STAGINGDIRECTORY%\appx
      working-directory: examples\windows\AppPackages\example

    - name: dir appx
      run: dir /s %BUILD_STAGINGDIRECTORY%\appx

    - name: Upload appx package
      uses: actions/upload-artifact@v2
      with:
        name: Example appx
        path: $(Build.StagingDirectory)\appx\*

  package:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: yarn install
      run: yarn install 
    - name: build TS
      run: yarn build

    - name: build Release x64
      run: msbuild /restore /p:RestorePackagesConfig=true package\windows\ReactNativeXaml.sln /p:configuration=Release /p:platform=x64

    - name: Validate size
      shell: powershell
      run: |
        $size = (gci package\windows\x64\Release\ReactNativeXaml\ReactNativeXaml.dll).Length
        $size
        if ($size -gt 1.5MB) {
          throw "DLL is bigger than 1.5MB"
        }

    - name: npm pack
      run: npm pack
      working-directory: package

    - name: mkdir npm 
      run: md %BUILD_STAGINGDIRECTORY%\npm
      
    - name: Copy npm package
      run: copy *.tgz %BUILD_STAGINGDIRECTORY%\npm

    - name: dir npm
      run: dir /s %BUILD_STAGINGDIRECTORY%\npm

    - name: Upload npm package
      uses: actions/upload-artifact@v2
      with:
        name: npm package
        path: $(Build.StagingDirectory)\npm\*

