# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  codegen:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: run CodeGen
      run: dotnet run 
      working-directory: codegen\Codegen

    - name: verify no changes from CodeGen
      shell: powershell
      run: |
        $changed = git status --porcelain=v1
        if ($changed -ne $null) { throw "CodeGen detected changes" }


  withJS:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: yarn install
      run: yarn install
 
    - name: build TS
      run: yarn build
      

  example:
    runs-on: windows-latest
    needs: withJS
    steps:
    - uses: actions/checkout@v2

    - name: build example
      run: yarn windows --no-launch --no-deploy --no-packager --logging
      working-directory: example

  package:
    runs-on: windows-latest
    needs: withJS
    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: build Release x64
      run: msbuild /restore /p:RestorePackagesConfig=true package\windows\ReactNativeXaml.sln /p:configuration=Release /p:platform=x64

    - name: Validate size
      shell: powershell
      run: |
        $size = (gci package\windows\x64\Release\ReactNativeXaml\ReactNativeXaml.dll).Length
        $size
        if ($size -gt 1.5MB) {
          throw "DLL is bigger than 1.5MB"
        }
