# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'

    - name: NuGet restore
      run: nuget restore example\windows\example.sln

    - name: run CodeGen
      run: dotnet run -verbose -winmd ..\..\example\windows\packages\Microsoft.UI.Xaml.2.6.0\lib\uap10.0\Microsoft.UI.Xaml.winmd
      working-directory: package\Codegen

    - name: verify no changes from CodeGen
      shell: powershell
      run: |
        $changed = git status --porcelain=v1
        if ($changed -ne $null) { throw "CodeGen detected changes" }

    - name: yarn install
      run: yarn install

    - name: build TS
      run: yarn build
    
    - name: publish to npm
      run: npm publish package
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
